name: Codeclimate Coverage
description: Submits coverage reports to Codeclimate
author: https://github.com/avantcredit
requirements: []
configuration:
  properties:
    sum_and_upload: boolean
    prefix: string
    test_reporter_url: string
